name: video_player_360
description: A flutter plugin to stream 360° videos on iOS and Android via a remote URL. The plugin uses the open source Google VR SDK.
version: 0.1.4
homepage: https://github.com/innovationmauritiustelecom/video_player_360

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.video_player_360
    pluginClass: VideoPlayer360Plugin

